name: PureConfig
baseurl: /v0.11.1
description: A boilerplate-free library for loading configuration files
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.11.1
org: com.github.pureconfig
markdown: kramdown
